### ISSUE TITLE
refactor: remove intermediate decimal and move decimal into PoSQL parser crate

### ISSUE THREAD

**Issue by Dustin-Ray** [spaceandtimelabs/sxt-proof-of-sql#113]
# Background and Motivation
Currently, the code handling decimal parsing and conversions is somewhat scattered. This issue seeks to resolve this by using the `bigdecimal::BigDecimal` type for as much as possible.

Important Note: the `BigDecimal` type does not trim leading and trailing zeros. Care should be taken when dealing with this.

# Requested Changes
To resolve this issue, we should:
- [ ] Add a `BigDecimalExt` extension trait in the `proof_of_sql::base::math` module. It should have, at minimum,
    - [ ] `precision` and `scale` methods akin to the existing `IntermediateDecimal::precision` and `IntermediateDecimal::scale` methods. NOTE: the precision and scale should be the values _after_ trimming any leading and trailing zeros. This is what the current implementation (implicitly) does.
    - [ ] a `try_into_scalar_with_precision_and_scale` method akin to the exiting `try_into_to_scalar` function.
- [ ] Eliminate the `proof_of_sql_parser::intermediate_decimal::IntermediateDecimal` and `proof_of_sql::base::math::decimal::Decimal` types, in favor of using `bigdecimal::BigDecimal` along with the `BigDecimalExt` extension trait.

Optional:
- [ ] Other refactoring and/or cleanup is welcome, but not immediately clear to me what should be done. These likely should be done in a follow up PR/issue. Some possibilities are:
    - [ ] It is not clear if the `DecimalError` enum is needed or if `bigdecimal::ParseBigDecimalError` or similar is sufficient.
    - [ ] The `scale_scalar` function should likely be moved into the `proof_of_sql::base::scalar` module.

**Comment by JayWhite2357** [comment]
To resolve this issue, we should:
- [ ] Add a `BigDecimalExt` extension trait in the `proof_of_sql::base::math` module. It should have, at minimum,
    - [ ] `precision` and `scale` methods akin to the existing `IntermediateDecimal::precision` and `IntermediateDecimal::scale` methods.
    - [ ] a `try_into_scalar_with_precision_and_scale` method akin to the exiting `try_into_to_scalar` function.
- [ ] Eliminate the `proof_of_sql_parser::intermediate_decimal::IntermediateDecimal` and `proof_of_sql::base::math::decimal::Decimal` types, in favor of using `bigdecimal::BigDecimal` along with the `BigDecimalExt` extension trait.

Optional:
- [ ] Other refactoring and/or cleanup is welcome, but not immediately clear to me what should be done. These likely should be done in a follow up PR/issue. Some possibilities are:
    - [ ] It is not clear if the `DecimalError` enum is needed or if `bigdecimal::ParseBigDecimalError` or similar is sufficient.
    - [ ] The `scale_scalar` function should likely be moved into the `proof_of_sql::base::scalar` module.

**Comment by JayWhite2357** [comment]
\bounty $250

**Comment by Gmin2** [comment]
@JayWhite2357 if this is still open to attempt?

**Comment by JayWhite2357** [comment]
This is blocking me at the moment, and none of the active PRs are passing CI or appear to be close enough to complete this quickly enough. I am closing the bounty in favor of https://github.com/spaceandtimelabs/sxt-proof-of-sql/pull/283.

**Comment by hp77-creator** [comment]
Hi @JayWhite2357 , this issue is resolved, right?

**Comment by JayWhite2357** [comment]
@hp77-creator correct.
