### ISSUE TITLE
MontScalar infallible conversions for trivial types

### ISSUE THREAD

**Issue by Dustin-Ray** [spaceandtimelabs/sxt-proof-of-sql#146]
Is there a reason why we need a try_from on any of the unsigned integer types? Seems to me that anything 64 bits and under should be able to be infallibly converted to Scalar, since those bit widths should always fit. Maybe we choose a scalar someday around 128 bits but that seems unlikely as well.

Feels kind of wrong to keep having to .expect() these conversions like so:

```rust
S::try_from(i.into()).expect("u8 value will always fit into S") + alpha
```

Maybe we just need to add these From conversions somewhere in [here](https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/dbe91428c2f4d2d2d6b409aa6d3971662e47e8ec/crates/proof-of-sql/src/base/scalar/mont_scalar_from.rs#L1-L58):

I see something here that converts a slice of bytes to MontScalar, I just need individual bytes, so maybe we can put it in here with something similar to this:

```rust
impl<T: MontConfig<4>> From<&[u8]> for MontScalar<T> {
    fn from(x: &[u8]) -> Self {
        if x.is_empty() {
            return Self::zero();
        }

        let hash = blake3::hash(x);
        let mut bytes: [u8; 32] = hash.into();
        bytes[31] &= 0b00001111_u8;

        Self::from_le_bytes_mod_order(&bytes)
    }
}
```

Although this appears to be taking the hash of the slice and converting that result into MontScalar.

**Comment by JayWhite2357** [comment]
The `Scalar` trait has many infallible conversions as bounds. In this particular case, I believe that the `+ for<'a> core::convert::From<&'a u8>` conversion just needed to be added, which is already implemented for `MontScalar`.

We certainly _could_ add conversions from [u8; N] arrays where `N < 32`, but I don't think we are in need of it.
See https://github.com/spaceandtimelabs/sxt-proof-of-sql/pull/141#discussion_r1759635797.
