### ISSUE TITLE
todo tracker

### ISSUE THREAD

**Issue by Dustin-Ray** [spaceandtimelabs/sxt-proof-of-sql#150]
There are a few todos spread throughout the repo, most of them are notating planned features that are not yet supported. See #149 for a few TimeStamp related todo!()s that actually would cause a panic under certain conditions.

Here are a few non-panicking todos labelled in doc comments throughout the repo that may or may not need some attention:

https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/6740144a5d3d01583d264d2560e68ff5f0025b22/crates/proof-of-sql/README.md?plain=1#L104

https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/6740144a5d3d01583d264d2560e68ff5f0025b22/crates/proof-of-sql/src/base/commitment/column_commitments.rs#L355

https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/6740144a5d3d01583d264d2560e68ff5f0025b22/crates/proof-of-sql/src/base/commitment/column_commitments.rs#L429

https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/6740144a5d3d01583d264d2560e68ff5f0025b22/crates/proof-of-sql/src/base/commitment/table_commitment.rs#L517

https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/6740144a5d3d01583d264d2560e68ff5f0025b22/crates/proof-of-sql/src/proof_primitive/mod.rs#L1

https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/6740144a5d3d01583d264d2560e68ff5f0025b22/crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs#L208

https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/6740144a5d3d01583d264d2560e68ff5f0025b22/crates/proof-of-sql/src/sql/proof/mod.rs#L1

Work is currently underway on range check which should resolve this, see #141
https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/6740144a5d3d01583d264d2560e68ff5f0025b22/crates/proof-of-sql/src/sql/proof_exprs/sign_expr.rs#L41

https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/6740144a5d3d01583d264d2560e68ff5f0025b22/crates/proof-of-sql/tests/integration_tests.rs#L494

https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/6740144a5d3d01583d264d2560e68ff5f0025b22/crates/proof-of-sql-parser/src/intermediate_ast_tests.rs#L253

https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/6740144a5d3d01583d264d2560e68ff5f0025b22/crates/proof-of-sql-parser/src/intermediate_ast_tests.rs#L773-L775

**Comment by drcapybara** [comment]
Adding the "good first issue" label because doc TODOs might be a good, easy place for someone to start with a contribution here.

**Comment by JayWhite2357** [comment]
Closing in favor of individual issues for each todo.
