### ISSUE TITLE
Enable `clippy::missing_panics_doc`

### ISSUE THREAD

**Issue by JayWhite2357** [spaceandtimelabs/sxt-proof-of-sql#163]
# Background and Motivation

In order to improve documentation and identify possible panics, we should enable clippy lints that warn when a function that panics but does not document this behavior.

# Requested Changes

- [ ] Enable `clippy::missing_panics_doc` lint.
- [ ] Add `#![cfg_attr(test, allow(clippy::missing_panics_doc))]` in order to not warn on `test`-only functions.
- [ ] Add documentation for every function violating this lint. (At the time of writing, this is 43 functions.)
- [ ] Set the `check-private-items = true` option.
- [ ] Add documentation for the private items violating this lint. (At the time of writing, this is 73 _additional_ functions.)

It is ok for this to be done in separate PRs. (e.g. one PR could enable the lint, and simply write `TODO: add panic docs` everywhere the warning appears.
NOTE: `allow(clippy::missing_panics_doc)` should only be used if a `panic` is actually impossible.

**Comment by JayWhite2357** [comment]
Closing in favor of the broader #182

**Comment by Gmin2** [comment]
can i get assigned to this @JayWhite2357 ?

**Comment by JayWhite2357** [comment]
@Gmin2 Yes. Can you please include an implementation plan with a time estimate?

FYI: to avoid confusion on this. It looks like there is a mismatch between my original GitHub comment and the adjusted bounty amount. I just updated the GitHub comment.

**Comment by Gmin2** [comment]
doing it by eod !
