### ISSUE TITLE
Return result from `Commitment::compute_commitments` rather than mutate parameter.

### ISSUE THREAD

**Issue by JayWhite2357** [spaceandtimelabs/sxt-proof-of-sql#165]
# Background and Motivation
Currently `Commitment::compute_commitments` mutates a slice buffer of commitments rather than returning a collection of the commitments. This is inherited from the behavior of the `blitzar` crate. However, it is more idiomatic for the implementations to return collections.

# Requested Changes

- [ ] Change the signature of `Commitment::compute_commitments` to be
```rust
fn compute_commitments(
    committable_columns: &[CommittableColumn],
    offset: usize,
    setup: &Self::PublicSetup<'_>,
) -> Vec<Self>;
```
- [ ] Update all implementers to reflect this.

**Comment by Gmin2** [comment]
/attempt #165

can i get assigned ?
