### ISSUE TITLE
test: replace `compute_commitment_for_testing` with `RistrettoPoint::compute_commitments`

### ISSUE THREAD

**Issue by JayWhite2357** [spaceandtimelabs/sxt-proof-of-sql#168]
# Background and Motivation
The `compute_commitment_for_testing` function was a utility function to simplify computing commitments for testing purposes. Newer interfaces simplify this code, so this function is no longer needed, and adds clutter.

# Requested Changes
- [ ] Replace `compute_commitment_for_testing` with `RistrettoPoint::compute_commitments`, which exists because of an `impl Commitment for RistrettoPoint`.

Note:
`compute_commitment_for_testing` could be refactored to leverage `Commitment::compute_commitments` like this:
```rust
let vals = iter_cast::<Curve25519Scalar, [u64; 4]>(slice_cast_to_iter(vals));
let mut commitments = [RistrettoPoint::default()];
Commitment::compute_commitments(
    &mut commitments,
    &[CommittableColumn::Scalar(vals)],
    offset_generators,
    &(),
);
commitments[0]
```

**Comment by Gmin2** [comment]
I thought this was $50 bounty :(
