### ISSUE TITLE
Enable `clippy::pedantic` lint group.

### ISSUE THREAD

**Issue by JayWhite2357** [spaceandtimelabs/sxt-proof-of-sql#182]
# Background and Motivation
We have `cargo clippy` running in our CI in order to enforce code quality. In order to increase our standards, we should enable the `clippy::pedantic` lint group.

# Requested Changes
- [ ] Add the `clippy::pedantic` lint to the bottom of the workspace `Cargo.toml` file.
- [ ] Refactor all of the code warnings so that clippy will pass.

NOTE: `clippy::pedantic` is very aggressive. It is possible that we will want to blanket `allow` some lints.

NOTE: please have good git hygiene on this issue. Make sure the individual commits on a PR are small and individually readable.

**Comment by abhishek818** [comment]
@JayWhite2357 can I get this assigned?

/attempt #182

**Comment by JayWhite2357** [comment]
@abhishek818 because `clippy::pedantic` is so aggressive, if there are things that you feel should be `allow`ed, bring it up in the comments here to discuss, or make notes in a PR for when we review.

**Comment by Gmin2** [comment]
@JayWhite2357 may i also throw my hate in this ?

**Comment by JayWhite2357** [comment]
@abhishek818 feel free to still work on this, but we have decided as a policy that you must have previously contributed to the project to be assigned an issue through the bounty program.
I've updated the bot message to reflect this.

**Comment by Gmin2** [comment]
@JayWhite2357 , i was investigating this issue and when running `clippy::pedantic` it gives 839 warnings , so do i need to resolve that manually  :( ?

**Comment by JayWhite2357** [comment]
@Gmin2 I believe that for a lot of them, you can use `cargo clippy --fix` to fix. But, yes, there is a lot of manual work that needs to go into this issue. (Hence the bounty amount.)
Some of the warnings may be too aggressive. If there is a particular lint that you think should be turned off, bring it up. I haven't looked too closely at everything.
