### ISSUE TITLE
Remove InnerProduct types from generic tests within base directory

### ISSUE THREAD

**Issue by stuarttimwhite** [spaceandtimelabs/sxt-proof-of-sql#230]
# Background and Motivation
Currently within the base directory (proof-of-sql/src/base), there is reference to 3 types: 
1. Curve25519Scalar
2. RistrettoPoint
3. InnerProductProof.

Any tests (within base) that use one of these 3 types to test a different type or function should be modified to remove these types. Note that some tests within base are actually meant to test one of these 3 types. These may be left alone for this issue. Non-test code should not be touched.

# Changes Required
For any of the 3 types that will be removed, replace each instance as follows:
1. Curve25519Scalar -> TestScalar
2. RistrettoPoint -> NaiveCommitment
3. InnerProductProof -> TestEvaluationProof

We recommend splitting the PR into 4 commits:
1. Scalar replacement
2. Commitment replacement (RistrettoPoint -> NaiveCommitment)
3. Proof replacement.
4. Everything else (to get build and tests passing).

NOTE: https://github.com/spaceandtimelabs/sxt-proof-of-sql/pull/197 is a partially completed version of this that is a bit out of date. It may or may not be a helpful reference point.

**Comment by Abiji-2020** [comment]
I would like to work on this issue 
/attempt #230

**Comment by JayWhite2357** [comment]
> I would like to work on this issue . In this we need to modify also the tests in each of the individual directories too in the modified form right ?
> 
> /attempt #230
> Options

Only the tests should be modified. See #144, which is essentially an almost completed version of this, but just needs to be finished.

**Comment by Abiji-2020** [comment]
> > I would like to work on this issue . In this we need to modify also the tests in each of the individual directories too in the modified form right ?
> > /attempt #230
> > Options
> 
> Only the tests should be modified. See #144, which is essentially an almost completed version of this, but just needs to be finished.

I got that the tests only should be modified in the base and we need not modify the tests that test these types. Am i correct?

**Comment by JayWhite2357** [comment]
> > > I would like to work on this issue . In this we need to modify also the tests in each of the individual directories too in the modified form right ?
> > > /attempt #230
> > > Options
> > 
> > 
> > Only the tests should be modified. See #144, which is essentially an almost completed version of this, but just needs to be finished.
> 
> I got that the tests only should be modified in the base and we need not modify the tests that test these types. Am i correct?

Correct. Also, I realized that I had referenced the wrong PR. The partially completed on is #197.

**Comment by Abiji-2020** [comment]
> > > > I would like to work on this issue . In this we need to modify also the tests in each of the individual directories too in the modified form right ?
> > > > /attempt #230
> > > > Options
> > > 
> > > 
> > > Only the tests should be modified. See #144, which is essentially an almost completed version of this, but just needs to be finished.
> > 
> > 
> > I got that the tests only should be modified in the base and we need not modify the tests that test these types. Am i correct?
> 
> Correct. Also, I realized that I had referenced the wrong PR. The partially completed on is #197.

Ok so in current modification is it okay that i creatr separate PR for each types so that it will be easy to review than checking all of them at once.

**Comment by JayWhite2357** [comment]
> Ok so in current modification is it okay that i creatr separate PR for each types so that it will be easy to review than checking all of them at once.

I'm pretty sure that there are some tests that require changing all 3 types at once.

The other option would be to create a separate commit for each type. That way, the reviewer can look at individual commits.

Alternatively, you could do smaller PRs/commits that do only one module/folder at a time.

**Comment by Abiji-2020** [comment]
> > Ok so in current modification is it okay that i creatr separate PR for each types so that it will be easy to review than checking all of them at once.
> 
> Thats a good idea, but I'm pretty sure that there are some tests that require changing all 3 types at once.
> 
> The other option would be to create a separate commit for each type. That way, the reviewer can look at individual commits.
> 
> Alternatively, you could do smaller PRs/commits that do only one module/folder at a time.

Ok than let me do smaller commits that do only module/ folder, then it will be easier for both of us...

**Comment by Abiji-2020** [comment]
@JayWhite2357 https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/crates/proof-of-sql/src/base/slice_ops/slice_cast_test.rs   in this test there are some test_cases where we are converting them to the  
 `Curve25519Scalar` type they should not be modified ? right

**Comment by JayWhite2357** [comment]
> we are not modifying the commitmentEvalutionProof to implement the TestEvaluationProof
If I understand the question, correct. We should not modify the tests that are testing the `InnerProductProof`. See #232 for a bit more context.
> we are also modifing the tests from a non-test file
I'm not sure what file you are referring to here. Can you be more specific?

**Comment by JayWhite2357** [comment]
> @JayWhite2357 https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/crates/proof-of-sql/src/base/slice_ops/slice_cast_test.rs in this test there are some test_cases where we are converting them to the `Curve25519Scalar` type they should not be modified ? right

I would modify only the ones that don't use the `curve25519_dalek::scalar::Scalar`.

**Comment by Abiji-2020** [comment]
> /attempt #230
> 
> Options

@Srayash this issue will be completed in the PR #264 as it was approved and waiting for the merge, would suggest to check up and work on other issues.
