### ISSUE TITLE
Tidy up `scalar` module

### ISSUE THREAD

**Issue by stuarttimwhite** [spaceandtimelabs/sxt-proof-of-sql#234]
# Background and Motivation
MontScalar and Scalar logic is currently disorganized. We should consolidate this logic.

**NOTE**: The following issues are likely to modify the same files, so be aware of potential merge conflicts with other PRs:

1. https://github.com/spaceandtimelabs/sxt-proof-of-sql/issues/232
2. https://github.com/spaceandtimelabs/sxt-proof-of-sql/issues/228

# Changes Required

- [x] Combine any logic held within the four files "mont_scalar", "mont_scalar_from", "mont_scalar_test", "mont_scalar_from_test" into two files "mont_scalar" and "mont_scalar_test".
- [x] Move the Scalar trait to its own "scalar" file within base/scalar.

**Comment by JayWhite2357** [comment]
Completed by #255
