### ISSUE TITLE
Remove `query!` macro.

### ISSUE THREAD

**Issue by JayWhite2357** [spaceandtimelabs/sxt-proof-of-sql#236]
# Background and Motivation

Rust macros are a bit of a anti-pattern. In particular, the `query!` macro, which is used as a testing utility macro to test `QueryExpr`, obfuscates the tests.

# Changes Required

- [ ] Remove uses of the `query!` macro and replace it with explicit uses of the tested methods. For example, https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/e2eb590ec5f100ae048c85474dc9f576901303cb/crates/proof-of-sql/src/sql/parse/query_expr_tests.rs#L1166-L1170 can be replaced by
    ```rust
    let query_text = "select max(i) max_sal, i0 d, count(i0) from t group by i0, i1 order by max_sal";
    let (t, accessor) = get_test_accessor();
    let intermediate_ast = SelectStatementParser::new().parse(query_text).unwrap();
    let query = QueryExpr::<NaiveCommitment>::try_new(intermediate_ast, t.schema_id(), &accessor).unwrap();
    ```
- [ ] Refactor or remove `get_test_accessor` so that it is explicit what the tables, columns, and data types are in the `SchemaAccessor`. For example, the above query has a `t` table with the columns `i`, `i0`, and `i1`, all with `BigInt` type. These columns should also be renamed to be slightly less generic and/or more helpful.
- [ ] Remove the `query!` macro.

NOTE: the macro is almost exclusively a macro that builds the query text. The actual functionality being tested should be essentially unchanged.

**Comment by akhilender-bongirwar** [comment]
/attempt #236

Maybe I didn't do this before that might be reason I was not awarded the bounty but it is written optional in the guidelines.
