### ISSUE TITLE
Isolate `arrow` code

### ISSUE THREAD

**Issue by JayWhite2357** [spaceandtimelabs/sxt-proof-of-sql#237]
# Background and Motivation

Currently, `arrow` is one of the elements that must be disabled to enable `no_std` support. Additionally, not every use-case requires arrow. So, we have gated it behind a features flag (`feature = "arrow"`). However, there are many instances of `#[cfg(feature = "arrow")]` throughout the codebase, which leave the code cluttered.

# Changes Required

- [ ] Move all arrow code to a single (or a small number) of modules.
    - My suggestion would be creating a new `proof_of_sql::base::arrow` module and moving all code there. However, this may not be possible, so this is not a hard requirement.
    - The resulting code _**must**_ not introduce cyclic dependencies and should resolve any existing ones with arrow related code. This is one of the primary reasons for this cleanup: in order to more easily identify and resolve these.
- [ ] Update any legacy documentation referencing arrow to ensure that it is up to date.
- [ ] Bump the `arrow` crate to version 53.

**Comment by stuarttimwhite** [comment]
> @stuarttimwhite @tlovell-sxt Is 53 the correct version for `arrow`?

Yes.

**Comment by melsonic** [comment]
@JayWhite2357 Hey, I have gone through the codebase and have some doubts.

I see some functions inside `struct implementation` have functions using the `arrow feature`. If we try to isolate only those functions under the `custom arrow module`, it will create cyclic dependencies. So, is moving the whole implementation to the `custom arrow module` ok?

**Comment by varshith257** [comment]
@melsonic I forgot to mark my attempt, I have started working on it and successfully isolated it to the custom arrow module. 

@JayWhite2357 I will submit multiple PRs to make the review process smooth. With this /attempt #237

**Comment by melsonic** [comment]
Hey @varshith257, I've spent some time reviewing the codebase, and as a result, So, I submitted a PR with my changes. The code is working fine, I have tested it, and only the documentation part is left, which I will do in the next commit. Since you have also worked on the issue, I am open to collaborating before the final changes if you are ok with it, let Jey decide.

**Comment by melsonic** [comment]
Hey @varshith257, I've also spent some time going through the codebase, and So, I have submitted a PR with my changes. The code is working fine, I have tested it, and only the documentation part is left, which I will do in the next commit. Since you have also worked on the issue, I am open to collaborating before the final changes if you are ok with it, else let Jay decide.

**Comment by varshith257** [comment]
@melsonic Cool! Let's collaborate. Yes, we have both spent time on it.  I think we have two different solutions, so let's see what @JayWhite2357 agree with and let's collaborate on it

**Comment by melsonic** [comment]
> @melsonic Cool! Let's collaborate. Yes, we have both spent time on it. I think we have two different solutions, so let's see what @JayWhite2357 agree with and let's collaborate on it

Yeah, sure. 
Solution is not that different, only difference is the structure. I also started with the module `arrow` inside `base`, but after seeing some modules under `sql/proof`, I moved it outside `base`. 
And yeah, let's wait for @JayWhite2357 and then proceed with our changes.

**Comment by melsonic** [comment]
> @melsonic Cool! Let's collaborate. Yes, we have both spent time on it. I think we have two different solutions, so let's see what @JayWhite2357 agree with and let's collaborate on it

Sure bro! Let's colab.
And talking about the solution, it is not that different, only difference is the structure. I also started with the module `arrow` inside `base`, but after seeing some modules under `sql/proof`, I moved it outside `base`. 

And yeah, let's wait for @JayWhite2357 and then proceed with our changes.

**Comment by JayWhite2357** [comment]
Hey @melsonic and @varshith257. Sorry for the delay on this. I think #266 is more in-line with what I was hoping for:
> My suggestion would be creating a new `proof_of_sql::base::arrow` module and moving all code there. However, this may not be possible, so this is not a hard requirement.

I think it's ok to keep some of the arrow code inside `sql/proof` since most of it can either be eventually removed, or is test only.

**Comment by melsonic** [comment]
> Hey @melsonic and @varshith257. Sorry for the delay on this. I think #266 is more in-line with what I was hoping for:
> 
> > My suggestion would be creating a new `proof_of_sql::base::arrow` module and moving all code there. However, this may not be possible, so this is not a hard requirement.
> 
> I think it's ok to keep some of the arrow code inside `sql/proof` since most of it can either be eventually removed, or is test only.

Okay, no problem @JayWhite2357
