### ISSUE TITLE
Add unary negative (`-`) operator to the prover.

### ISSUE THREAD

**Issue by JayWhite2357** [spaceandtimelabs/sxt-proof-of-sql#238]
# Background and Motivation

The unary `-` operator is a important operator. As we expand support for all SQL, this is one of the pieces that we should have.

# Changes Required

- [ ] Add a `NegativeExpr` in `sql::proof_exprs`.
    - See `AddSubtractExpr` and `NotExpr` for good reference points.
    - [ ] Be sure to implement `ProofExpr`, add it to `DynProofExpr`, etc.
- [ ] Update the parser to handle the unary negative (`-`) operator.
- [ ] Test
    - [ ] Add unit tests for all net-new code.
    - [ ] Add end-to-end tests demonstrating that this operator is added.

**Comment by digital-phoenix** [comment]
@JayWhite2357 the parser already handles negation by mapping it to multiplying the expression by -1. What additional benefit does a negative operator provide?

**Comment by JayWhite2357** [comment]
> @JayWhite2357 the parser already handles negation by mapping it to multiplying the expression by -1. What additional benefit does a negative operator provide?

Hmmm... This is a good point. For some reason I had it marked down that we didn't support this.

Closing this issue as duplicate.
