### ISSUE TITLE
Set up coverage report in CI.

### ISSUE THREAD

**Issue by JayWhite2357** [spaceandtimelabs/sxt-proof-of-sql#239]
# Background and Motivation

Coverage reports help a lot with code quality and review.

# Changes Required

Add a code coverage workflow to the CI. There is no single way to do this, and some work will be needed to figure out a good reporting mechanism.

* References with varying ways to set it up:
    * https://doc.rust-lang.org/rustc/instrument-coverage.html#instrumentation-based-code-coverage
    * https://marco-c.github.io/2020/11/24/rust-source-based-code-coverage.html
* Tools:
    * https://crates.io/crates/grcov
    * https://crates.io/crates/cargo-tarpaulin
    * https://crates.io/crates/cargo-llvm-cov
* Services that help with reporting and perhaps other things:
    * codecov.io
    * coveralls.io

Some more clarification:
* The CI job should fail if the code coverage does not meet a threshold. (i.e. at least 90% coverage, or something similar).
* The CI logs should show some human readable output.
* I would much prefer to not _need_ an external service like Codecov to do the above. That should only be for visualization and deeper dives into job failures. (And should be added in a separate CP.)
* There are several features. We should make sure we are checking for coverage for all of the combinations of features. (i.e. are we actually testing all code?)
* For Codecov, etc. I will need to be the one setting up tokens/accounts, etc. So, be sure to add some documentation that explains how to do this, or links to a how to.

**Comment by varshith257** [comment]
/attempt #239

**Implementation Plan:**

To set up the coverage report in the CI pipeline, I am thinking of the following steps:

I plan to use cargo-tarpaulin as the coverage tool for this setup. It's widely used for Rust projects and provides good integration for CI environments.

**Comment by JayWhite2357** [comment]
> /attempt #239
> 
> **Implementation Plan:**
> 
> To set up the coverage report in the CI pipeline, I am thinking of the following steps:
> 
>     * [ ]   I plan to use llvm as the coverage tool for this setup. It's widely used for Rust projects and provides good integration for CI environments.
> 
>     * [ ]  I will also update the existing CI pipeline by adding a new job that runs tests with coverage. I will also ensure cargo-tarpaulin is installed and coverage reports will be generated.
> 
>     * [ ]  We can  integrate Codecov as the coverage reporting tool. Once the coverage report is generated, it will be uploaded to Codecov for detailed insights and visualization.

Sounds reasonable. Here's a few concerns (partially related to your PR). I'll add these to the original issue as clarification.
* The CI job should fail if the code coverage does not meet a threshold. (i.e. at least 90% coverage, or something similar).
* The CI logs should show some human readable output.
* I would much prefer to not _need_ an external service like Codecov to do the above. That should only be for visualization and deeper dives into job failures.
* There are several features. We should make sure we are checking for coverage for all of the combinations of features. (i.e. are we actually testing all code?)

**Comment by JayWhite2357** [comment]
Follow up issues
- [ ] We should update the CI so that the tests run more efficiently. (By removing long-running tests and/or ensuring there are no redundant runs.)
- [ ] We should add tests to bring the code coverage higher. (Perhaps one issue for each of 95%, 96%, 97%, etc.)

@varshith257 feel free to create these issues based on our conversations

**Comment by varshith257** [comment]
@JayWhite2357 Okay! I will create issues for the above.

I think the bounty need to be approved on algora dashboard still it shows pending

**Comment by JayWhite2357** [comment]
@varshith257 I was out of office the first half of the week, so was a bit slow on the payouts this time around. You should see it now.

**Comment by varshith257** [comment]
@JayWhite2357 Nope 😅

Thanks it has been awarded :)
