### ISSUE TITLE
Update examples to use the dynamic Dory commitment scheme.

### ISSUE THREAD

**Issue by JayWhite2357** [spaceandtimelabs/sxt-proof-of-sql#244]
# Background and Motivation

Our example code leverages the `InnerProductProof` commitment scheme. While this is still valid, it is more difficult as an entry point to the code because it requires Linux (and GPU by default).

# Changes Required

- [x] Update the examples (in `crates/proof-of-sql/examples`) to use the `DynamicDoryEvaluationProof` instead of the `InnerProductProof`.
- [ ] Ensure these examples run correctly with the `blitzar` feature disabled. (i.e. update the CI)
- [ ] Update the READMEs to add examples of how to run this with and without the `blitzar` feature enabled.

**Comment by Abiji-2020** [comment]
/attempt #244 

@JayWhite2357 I am new to RUST. Needed to modify all the examples in `crates/proof-of-sql/examples` to use DynamicDoryEvaluationProof right?

**Comment by JayWhite2357** [comment]
> /attempt #244
> 
> @JayWhite2357 I am new to RUST. Needed to modify all the examples in `crates/proof-of-sql/examples` to use DynamicDoryEvaluationProof right?
> Options

Yes, that is correct.

**Comment by Abiji-2020** [comment]
@JayWhite2357 I have updated the examples and checked on it the hello_wolrd example run perfectly and the posql_db had also run efficiently but on the verification it arises the error of MLE evaluations failed 

![image](https://github.com/user-attachments/assets/c644757f-6abd-4735-bf63-d127a248af45)

**Comment by JayWhite2357** [comment]
@Abiji-2020, see my comment here: https://github.com/spaceandtimelabs/sxt-proof-of-sql/pull/253#discussion_r1796337162.

**Comment by Abiji-2020** [comment]
@JayWhite2357 since the examples run without the `blitzer` feature ( which is not required ) is it necessary to add the examples to run with the `blitzer` feature enabled??

**Comment by Abiji-2020** [comment]
@JayWhite2357 In this how will i get the bounty, just curious 👀

**Comment by Abiji-2020** [comment]
> 💡 @Abiji-2020 submitted a [pull request](https://github.com/spaceandtimelabs/sxt-proof-of-sql/pull/253) that claims the bounty. You can [visit your bounty board](https://console.algora.io/org/spaceandtimelabs/bounties) to reward.

@JayWhite2357 Just curious that it was a `50$` bounty issue right ?👀

**Comment by JayWhite2357** [comment]
@Abiji-2020 I was out of office the first half of the week, so was a bit slow on the payouts this time around. You should see it now.

**Comment by Abiji-2020** [comment]
> @Abiji-2020 I was out of office the first half of the week, so was a bit slow on the payouts this time around. You should see it now.

yes it was updated, Thanks ❤️
